Don't retry builds, just report it

diff --git a/scripts/build.d/build-jellyfin b/scripts/build.d/build-jellyfin
--- a/scripts/build.d/build-jellyfin
+++ b/scripts/build.d/build-jellyfin
@@ -66,12 +66,10 @@ platforms=(
 )
 for platform in ${platforms[@]}; do
     ./build ${reponame} ${platform} &>${curdir}/../../logs/build-test/${platform}.log
-    if [[ ! -f $( find bin/${reponame}/${platform}/ -type f | head -1 ) ]]; then
-        # Try to build each one again if it fails the first time
-        ./build ${reponame} ${platform}
-    fi
-    if [[ ! -f $( find bin/${reponame}/${platform}/ -type f | head -1 ) ]]; then
-        echo "*** FAILED TO BUILD PLATFORM ${platform}"
+    if [[ $? -gt 0 ]]; then
+        echo "FAILED TO BUILD PLATFORM ${platform}"
+    else
+        echo "OK ${platform}"
     fi
 done
 
