Temporary

diff --git a/scripts/build.d/build-jellyfin b/scripts/build.d/build-jellyfin
--- a/scripts/build.d/build-jellyfin
+++ b/scripts/build.d/build-jellyfin
@@ -50,41 +50,44 @@ git submodule update --init || true
 
 popd
 
-echo "*** BUILDING OS PACKAGES ***"
-platforms=(
-    debian-package-x64 debian-package-arm64 debian-package-armhf
-    ubuntu-package-x64 ubuntu-package-arm64 ubuntu-package-armhf
-    fedora-package-x64
-    centos-package-x64
-    linux-x64
-    win-x64
-    win-x86
-    portable
-    macos
-)
-for platform in ${platforms[@]}; do
-    ./build ${reponame} ${platform} &>${builddir}/logs/${platform}.log
-    if [[ $? -gt 0 ]]; then
-        echo "FAILED TO BUILD PLATFORM ${platform}"
-    else
-        echo "OK ${platform}"
-    fi
-done
-
-echo "*** GRABBING WINDOWS INSTALLER FROM AZURE ***"
-installer_tmpdir="$( mktemp -d )"
-azure_build_id="$( az pipelines runs list --branch release-10.5.z --pipeline-ids 1 --reason batchedCI --result succeeded --status completed --query-order QueueTimeDesc --top 1 | jq '.[].id' )"
-az pipelines runs artifact download --artifact-name 'Jellyfin Server Setup' --path ${installer_tmpdir} --run-id ${azure_build_id} && \
-mkdir -p bin/jellyfin/win-installer && \
-mmv "${installer_tmpdir}/jellyfin_*_windows-*.exe" "bin/jellyfin/win-installer/jellyfin_${tagname}-#2.exe" && \
-rm -rf ${installer_tmpdir} || \
-echo "FAILED TO GRAB A WINDOWS EXE, FIX THIS MANUALLY PL0X."
-
-echo "*** SYNCING OS PACKAGES TO REPO ***"
-rsync -avz bin/${reponame}/ ${repodir}/incoming/${reponame}_${tagname}
-
-echo "*** COLLECTING PACKAGES FOR REPO ***"
-sudo ${repodir}/collect-server.sh ${repodir}/incoming/${reponame}_${tagname}
+#echo "*** BUILDING OS PACKAGES ***"
+#platforms=(
+#    debian-package-x64 debian-package-arm64 debian-package-armhf
+#    ubuntu-package-x64 ubuntu-package-arm64 ubuntu-package-armhf
+#    fedora-package-x64
+#    centos-package-x64
+#    linux-x64
+#    win-x64
+#    win-x86
+#    portable
+#    macos
+#)
+#for platform in ${platforms[@]}; do
+#    ./build ${reponame} ${platform} &>${builddir}/logs/${platform}.log
+#    if [[ $? -gt 0 ]]; then
+#        echo "FAILED TO BUILD PLATFORM ${platform}"
+#    else
+#        echo "OK ${platform}"
+#    fi
+#done
+#
+#echo "*** GRABBING WINDOWS INSTALLER FROM AZURE ***"
+#installer_tmpdir="$( mktemp -d )"
+#azure_build_id="$( az pipelines runs list --branch release-10.5.z --pipeline-ids 1 --reason batchedCI --result succeeded --status completed --query-order QueueTimeDesc --top 1 | jq '.[].id' )"
+#az pipelines runs artifact download --artifact-name 'Jellyfin Server Setup' --path ${installer_tmpdir} --run-id ${azure_build_id} && \
+#mkdir -p bin/jellyfin/win-installer && \
+#mmv "${installer_tmpdir}/jellyfin_*_windows-*.exe" "bin/jellyfin/win-installer/jellyfin_${tagname}-#2.exe" && \
+#rm -rf ${installer_tmpdir} || \
+#echo "FAILED TO GRAB A WINDOWS EXE, FIX THIS MANUALLY PL0X."
+#
+#echo "*** SYNCING OS PACKAGES TO REPO ***"
+#rsync -avz bin/${reponame}/ ${repodir}/incoming/${reponame}_${tagname}
+#
+#echo "*** COLLECTING PACKAGES FOR REPO ***"
+#sudo ${repodir}/collect-server.sh ${repodir}/incoming/${reponame}_${tagname}
+#
+#echo "*** CLEAN UP DOCKER IMAGES ***"
+#docker image rm -f $( docker images -aq ) || true
 
 echo "*** BUILDING DOCKER IMAGES ***"
 /bin/bash ${builddir}/scripts/build.d/build-jellyfin-docker tag-name=${tagname} build-docker-manifests=yes
